export const robloxPayoutConfigKeys = new Set([
  'PANEL_COMMAND_NAME',
  'ROBUX_ENABLED',
  'ROBUX_RATE',
  'ROBUX_PACKAGES',
  'ROBUX_PAYOUT_COOLDOWN_SECONDS',
  'ROBUX_NOTIFICATION_CHANNEL_ID',
  'ROBUX_SUCCESS_NOTIFICATION_CHANNEL_ID',
  'ROBUX_ERROR_NOTIFICATION_CHANNEL_ID',
  'ROBUX_RECEIPT_CHANNEL_ID',
  'ROBLOX_GROUPS',
  'ROBLOX_CREDENTIALS',
  'ROBUX_PANELS',
])
