import {ActionRowBuilder,EmbedBuilder,MessageFlags,ModalBuilder,PermissionFlagsBits,SlashCommandBuilder,TextInputBuilder,TextInputStyle,type ChatInputCommandInteraction,type GuildMember,type Interaction,type ModalSubmitInteraction} from "discord.js";
import type {FeatureContext,FeatureModule,MemberSpendingStore} from "../../types.js";
import {createOwnDatabaseStore} from "./store.js";

export const memberSpendingFeature:FeatureModule={runtimeKey:"member-spending",version:"1.0.0",intents:["Guilds","GuildMembers"],async activate(context){
  const own=bool(context.config.SPENDING_DB_USE_OWN,false);let external:Awaited<ReturnType<typeof createOwnDatabaseStore>>|undefined;
  const store:MemberSpendingStore=own?(external=await createOwnDatabaseStore(requiredSecret(context.secrets.SPENDING_DB_URL),context.botId)):context.memberSpending;
  let stopped=false;
  const onInteraction=(i:Interaction)=>{const task=i.isChatInputCommand()&&i.commandName==="spending"?command(context,store,i):i.isModalSubmit()&&i.customId.startsWith("spending:update:")?update(context,store,i):null;if(task)void task.catch(e=>respondError(i,e));};
  context.client.on("interactionCreate",onInteraction);context.client.once("clientReady",()=>{if(!stopped)void register(context).catch(e=>{console.error("Member Spending command registration failed",e);void context.reportFeatureError("COMMAND_REGISTRATION_FAILED",e);});});
  return async()=>{stopped=true;context.client.off("interactionCreate",onInteraction);await external?.close();};
}};

async function command(c:FeatureContext,s:MemberSpendingStore,i:ChatInputCommandInteraction){if(!i.inGuild())return;if(!c.permissions.canUse(i,`spending/${i.options.getSubcommand()}`,i.memberPermissions?.has(PermissionFlagsBits.Administrator)===true))return i.reply({content:"คุณไม่มีสิทธิ์ใช้คำสั่งนี้",flags:MessageFlags.Ephemeral});const sub=i.options.getSubcommand();
  const guild=i.guild!;
  if(sub==="add"){const user=i.options.getUser("member",true),baht=i.options.getInteger("amount",true);await i.deferReply({flags:MessageFlags.Ephemeral});const e=await s.add(user.id,baht*100),member=await guild.members.fetch(user.id).catch(()=>null);if(member)await applyRoles(c,member,e.amountSatang,e.txCount);const payload=render(c,e.txCount===1?"first_card":"returning_card",vars(user.id,member?.displayName??user.username,baht*100,e));if(i.channel?.isTextBased()&&"send" in i.channel)await i.channel.send(payload as never);await i.editReply("อัปเดตบัตรสะสมเรียบร้อย");return;}
  if(sub==="update"){const user=i.options.getUser("member",true);await i.showModal(new ModalBuilder().setCustomId(`spending:update:${user.id}`).setTitle("แก้ไขยอดสะสม").addComponents(row("amount","ยอดรวม (บาท) เว้นว่าง=ไม่เปลี่ยน",false),row("count","จำนวนครั้ง เว้นว่าง=ไม่เปลี่ยน",false)));return;}
  const user=i.options.getUser("member")??i.user;
  if(sub==="delete"){await i.reply({content:await s.remove(user.id)?`ลบข้อมูล <@${user.id}> แล้ว`:"ไม่พบข้อมูลสมาชิก",flags:MessageFlags.Ephemeral});return;}
  if(sub==="check"){const e=await s.get(user.id)??{memberDiscordId:user.id,amountSatang:0,txCount:0};await i.reply({embeds:[new EmbedBuilder().setTitle("บัตรสะสม").setDescription(`<@${user.id}>\nยอดสะสม **${money(e.amountSatang)} บาท** · ${e.txCount} ครั้ง`)],flags:MessageFlags.Ephemeral});return;}
  if(sub==="total"){const e=await s.totals();await i.reply({content:`ยอดรวม ${money(e.amountSatang)} บาท · ${e.txCount} ครั้ง`,flags:MessageFlags.Ephemeral});return;}
  const board=await s.leaderboard(sub==="rank"?5:20);await syncRankRoles(c,guild,board);const lines=board.map((e,n)=>`${n+1}. <@${e.memberDiscordId}> — ${money(e.amountSatang)} บาท · ${e.txCount} ครั้ง`).join("\n")||"ยังไม่มีข้อมูล";await i.reply(render(c,"leaderboard",{leaderboard_lines:lines,member_count:String(board.length)}) as never);
}
async function update(c:FeatureContext,s:MemberSpendingStore,i:ModalSubmitInteraction){if(!i.inGuild()||!i.memberPermissions?.has(PermissionFlagsBits.Administrator))return i.reply({content:"ไม่มีสิทธิ์",flags:MessageFlags.Ephemeral});const id=i.customId.slice("spending:update:".length),amount=parseOptional(i.fields.getTextInputValue("amount"),100),count=parseOptional(i.fields.getTextInputValue("count"),1);if(amount===undefined&&count===undefined)return i.reply({content:"กรุณากรอกอย่างน้อยหนึ่งช่อง",flags:MessageFlags.Ephemeral});const e=await s.set(id,{...(amount!==undefined?{amountSatang:amount}:{}),...(count!==undefined?{txCount:count}:{})});await i.reply({content:`ตั้งยอด <@${id}> เป็น ${money(e.amountSatang)} บาท · ${e.txCount} ครั้ง`,flags:MessageFlags.Ephemeral});}
async function register(c:FeatureContext){if(!c.guildId)throw new Error("Discord guild is not configured");const guild=await c.client.guilds.fetch(c.guildId);const cmd=new SlashCommandBuilder().setName("spending").setDescription("จัดการบัตรสะสมยอดใช้จ่ายแบบกรอกเอง");cmd.addSubcommand(x=>x.setName("add").setDescription("เพิ่มยอดสะสม").addUserOption(o=>o.setName("member").setDescription("สมาชิก").setRequired(true)).addIntegerOption(o=>o.setName("amount").setDescription("จำนวนเงินบาท").setMinValue(1).setRequired(true)));cmd.addSubcommand(x=>x.setName("update").setDescription("แก้ไขยอดรวม/จำนวนครั้ง").addUserOption(o=>o.setName("member").setDescription("สมาชิก").setRequired(true)));for(const [name,desc] of [["delete","ลบข้อมูล"],["check","ตรวจสอบบัตร"]] as const)cmd.addSubcommand(x=>x.setName(name).setDescription(desc).addUserOption(o=>o.setName("member").setDescription("สมาชิก").setRequired(name==="delete")));cmd.addSubcommand(x=>x.setName("list").setDescription("อันดับยอดสะสม"));cmd.addSubcommand(x=>x.setName("total").setDescription("ยอดรวมทั้งหมด"));cmd.addSubcommand(x=>x.setName("rank").setDescription("รีเฟรชยศ Top 1 / Top 5"));await guild.commands.create(cmd.toJSON());}

async function applyRoles(c:FeatureContext,m:GuildMember,amount:number,count:number){const first=id(c.config.SPENDING_FIRST_ROLE_ID);if(first)await safeRole(m,first,true);const tiers=Array.isArray(c.config.SPENDING_UPGRADE_TIERS)?c.config.SPENDING_UPGRADE_TIERS.flatMap(x=>isRecord(x)&&Number(x.amount)>0&&id(x.roleId)?[{amount:Number(x.amount)*100,roleId:id(x.roleId)!}]:[]):[];const qualified=tiers.filter(t=>amount>=t.amount||(bool(c.config.SPENDING_COUNT_ENABLED,false)&&count>=num(c.config.SPENDING_UPGRADE_COUNT,5)));if(bool(c.config.SPENDING_TIER_STACK,true)){for(const t of qualified)await safeRole(m,t.roleId,true);}else for(const t of tiers)await safeRole(m,t.roleId,t===qualified.at(-1));}
async function syncRankRoles(c:FeatureContext,guild:NonNullable<ChatInputCommandInteraction["guild"]>,board:Awaited<ReturnType<MemberSpendingStore["leaderboard"]>>){const top1=id(c.config.SPENDING_TOP1_ROLE_ID),top5=id(c.config.SPENDING_TOP5_ROLE_ID);if(!top1&&!top5)return;const members=await guild.members.fetch();for(const m of members.values()){if(top1)await safeRole(m,top1,m.id===board[0]?.memberDiscordId);if(top5)await safeRole(m,top5,board.slice(1,5).some(e=>e.memberDiscordId===m.id));}}
async function safeRole(m:GuildMember,roleId:string,add:boolean){const role=m.guild.roles.cache.get(roleId),me=m.guild.members.me;if(!role||!me?.permissions.has(PermissionFlagsBits.ManageRoles)||me.roles.highest.comparePositionTo(role)<=0)return;if(add&&!m.roles.cache.has(roleId))await m.roles.add(roleId);if(!add&&m.roles.cache.has(roleId))await m.roles.remove(roleId);}
function render(c:FeatureContext,slot:string,v:Record<string,string>):Record<string,unknown>{const raw=isRecord(c.presentations[slot])?c.presentations[slot]:{};if(raw.mode==="COMPONENTS_V2"&&Array.isArray(raw.components))return{flags:MessageFlags.IsComponentsV2,components:deep(raw.components,v)};if(raw.mode==="EMBED"&&Array.isArray(raw.embeds))return{content:fill(String(raw.content??""),v)||undefined,embeds:deep(raw.embeds,v)};return{embeds:[new EmbedBuilder().setColor(0xe46daf).setTitle(fill(String(raw.title??"บัตรสะสมของ {{member}}"),v)).setDescription(fill(String(raw.description??"ยอดรอบนี้ {{today}} บาท\nยอดสะสม {{total}} บาท · {{count}} ครั้ง"),v)).setThumbnail(v.avatar??null)]};}
function vars(uid:string,name:string,today:number,e:{amountSatang:number;txCount:number}){return{member:name,member_mention:`<@${uid}>`,today:money(today),total:money(e.amountSatang),count:String(e.txCount),avatar:`https://cdn.discordapp.com/embed/avatars/0.png`};}
function deep(x:unknown,v:Record<string,string>):unknown{if(typeof x==="string")return fill(x,v);if(Array.isArray(x))return x.map(y=>deep(y,v));if(isRecord(x))return Object.fromEntries(Object.entries(x).map(([k,y])=>[k,deep(y,v)]));return x;}function fill(x:string,v:Record<string,string>){return x.replace(/\{\{([a-z0-9_]+)}}/gi,(_,k:string)=>v[k]??"");}
function row(customId:string,label:string,required:boolean){return new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId(customId).setLabel(label).setStyle(TextInputStyle.Short).setRequired(required));}function parseOptional(x:string,m:number){if(!x.trim())return undefined;if(!/^\d+(?:\.\d{1,2})?$/.test(x.trim()))throw new Error("กรุณากรอกตัวเลขที่ไม่ติดลบ");return Math.round(Number(x)*m);}function money(x:number){return(x/100).toLocaleString("th-TH",{minimumFractionDigits:2,maximumFractionDigits:2});}function bool(x:unknown,f:boolean){return typeof x==="boolean"?x:f;}function num(x:unknown,f:number){return typeof x==="number"?x:f;}function id(x:unknown){const s=String(x??"");return/^\d{15,30}$/.test(s)?s:undefined;}function requiredSecret(x:unknown){if(typeof x!=="string"||!/^postgres(?:ql)?:\/\//i.test(x))throw new Error("SPENDING_DB_URL must be a PostgreSQL connection URL");return x;}function isRecord(x:unknown):x is Record<string,unknown>{return!!x&&typeof x==="object"&&!Array.isArray(x);}async function respondError(i:Interaction,e:unknown){if(!i.isRepliable())return;const content=`ทำรายการไม่สำเร็จ: ${e instanceof Error?e.message:"Unknown error"}`;if(i.deferred||i.replied)await i.editReply(content).catch(()=>{});else await i.reply({content,flags:MessageFlags.Ephemeral}).catch(()=>{});}
